version: "3.2"
services:
  web:
    build: ./app
    ports:
      - "8080:8080"
    volumes:
      - ./app:/usr/local/app
      - /usr/local/app/venv/
    container_name: pdf-converter
    environment:
      - DEBUG=1

  gcloud-tasks-emulator:
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    command: -host 0.0.0.0 -port 8123 -queue "projects/dev/locations/here/queues/anotherq"
    ports:
      - "${TASKS_PORT:-8123}:8123"