version: "3.2"
services:
  web:
    build: ./app
    ports:
      - "8080:8080"
    volumes:
      - ./app:/usr/local/app
      - /usr/local/app/venv/
      - type: volume
        source: site-packages
        target: /usr/local/lib/python3.8/site-packages
    container_name: pdf-converter
    environment:
      - DEBUG=1
      - FIRESTORE_EMULATOR_HOST=firestore_emulator:8200
      - FIRESTORE_PROJECT_ID=dev
      - TASK_EMULATOR_HOST=gcloud-tasks-emulator:8123
      - WEB_HOST=http://web:8080
    depends_on:
      - firestore_emulator
      - gcloud-tasks-emulator
    

  gcloud-tasks-emulator:
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    command: -host 0.0.0.0 -port 8123 -queue "projects/dev/locations/here/queues/anotherq"
    ports:
      - "${TASKS_PORT:-8123}:8123"
  
  firestore_emulator:
      image: mtlynch/firestore-emulator
      environment:
        - FIRESTORE_PROJECT_ID=dev
        - PORT=8200

volumes:
  site-packages: