version: "3.2"
services:
  web:
    image: pdfconv
    build: ./app
    ports:
      - "8080:8080"
    volumes:
      - ./app:/usr/local/app
      - /usr/local/app/venv/
    entrypoint:
      [
        "gunicorn",
        "--bind", "0.0.0.0:8080",
        "--workers", "3",
        "main:app",
        --access-logfile, "-",
        "--reload",
      ]
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./service_account/your_service_account.json
      - FIRESTORE_EMULATOR_HOST=firebase_emulator:8200
      - GOOGLE_CLOUD_PROJECT=${PROJECT_ID}
      - FIRESTORE_PROJECT_ID=${PROJECT_ID}
      - TASK_EMULATOR_HOST=gcloud-tasks-emulator:8123
      - WEB_HOST=http://web:8080
      - FLASK_ENV=development
    depends_on:
      - firebase_emulator
      - gcloud-tasks-emulator
    restart: on-failure

  gcloud-tasks-emulator:
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    command: -host 0.0.0.0 -port 8123 -queue "projects/${PROJECT_ID}/locations/us-central1/queues/default"
    ports:
      - "${TASKS_PORT:-8123}:8123"

  firebase_emulator:
    image: firebase
    build:
      context: ./firebase
      dockerfile: Dockerfile.firebase
    ports:
      - 4000:4000 # Emulator Suite UI
      - 8200:8200 # Cloud Firestore
    command:
      [
        "firebase",
        "--project=${PROJECT_ID}",
        "emulators:start",
        "--import",
        "./storage",
        "--export-on-exit",
        "./storage",
      ]
    volumes:
      - ./.cache/bin/:/root/.cache:cached
      - ./.cache/config/:/root/.config:cached
      - ./firebase:/usr/local/db

