# Generated by Django 2.2.1 on 2019-05-10 22:03

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Task Name')),
                ('doc', models.FileField(upload_to='', validators=[main.validators.validate_size])),
            ],
        ),
    ]
