# Generated by Django 2.2.1 on 2019-05-17 19:22

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='doc',
            field=models.FileField(upload_to='', validators=[main.validators.validate_size, main.validators.validate_content]),
        ),
    ]
