name: Deploy to Cloud run and Firebase
on:
  push:
    branches:
      - master
jobs:
  setup-build-publish-deploy-firebase:
    name: Deploy assets to Firebase
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Front end assets
      run: |
        ./scripts/build.sh assets

    - name: Deploy to firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}'
        projectId: pdf-conv-3d1f5
        channelId: live
        entryPoint:  ./firebase

  setup-build-publish-deploy-cloudrun:
    name: Deploy PDF service to cloud run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_CREDENTIALS }}
        export_default_credentials: true
    
    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: Rebuild Docker image
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      run: |
        ./scripts/build.sh app

    - name: Deploy to cloud run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@main
      with:
        service: default
        image: gcr.io/${{ secrets.GCP_PROJECT }}/pdf-conv:latest
        credentials: ${{ secrets.SERVICE_ACCOUNT_CREDENTIALS }}
        region: us-central1

    - run: echo "${{ steps.deploy.outputs.url }}"