name: Deploy to Cloud run and Firebase
on:
  push:
    branches:
      - main
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true
    
    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
      
    # Set GCP Project
    - name: Set Project
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}
      
    # Build and Deploy to both Cloud Run and Firebase
    - name: Build and Deploy
      run: |
        ./scripts/deploy.sh